### ISSUE TITLE
VBoxNetLwf driver is missing

### ISSUE THREAD

**Issue by newsoft** [Winbagility/Winbagility#14]
Running loadall.cmd from VBoxBin-r3.7z release:

Installing INF file "V:\VBoxBin\VBoxNetLwf.inf" ...
VBoxNetCfgWinInfInstall failed, hr (0x80070002)
Installation failed, rolling back installation set ...
Rollback complete
error installing VBoxNetLwf (0x80070002)

The driver is effectively missing.

**Comment by Winbagility** [comment]
Hello,

did you try to change loadall.sh@38 from:
for drv in VBoxNetAdp VBoxNetAdp6 VBoxNetFlt VBoxNetLwf VBoxUSBMon VBoxUSB VBoxDrv;
to:
for drv in VBoxNetAdp VBoxNetAdp6 VBoxNetFlt VBoxUSBMon VBoxUSB VBoxDrv;

I know, this tool is not for script kiddie... I'm sorry about that... 

I will do my best !

Good luck !

And because I'm not sure that you are able to do that here is the tutorial :
1. Open an explorer to the directory where loadall.sh is.
2. In the navigation bar type : "cmd" and then press enter
3. You should see a black window pops-up, don't be afraid, your are now a 1337 HAX0R
4. In this black window type : "notepad loadall.sh"
5. search & replace the line 
6. Put your finger on Ctrl (the key next the Windows one), and keep it on it, and at the same time press S. When I said "Put", a better word is press.
![keyboard](https://user-images.githubusercontent.com/31218600/58043983-f6c7f880-7b3e-11e9-955f-3a8df48eef87.jpg)

7. Try again.

I edited this comment just to be sure that this guy saves the file.

**Comment by Winbagility** [comment]
More seriously, I expected at least a pull request for the EPT duplication from you...

**Comment by newsoft** [comment]
If I was a hacker, I would probably try to edit random stuff until it works.

But since I am a software engineer, I'd rather rely on the project owner to confirm what is the purpose of that driver, and if the absence of that driver could lead to spurious and hard-to-debug issues later on (e.g. I would expect networking issues, given the name of that driver).

A thorough root cause analysis of the issue could also possibly lead to improvements in the way your project is tested and packaged - like having individual files checked in rather than a single binary blob. Then I could send a PR to get that script fixed.

PS. I was expecting apologies (maybe) but definitely not sarcasm. And my terminal does not have a black background, as I don't find it eye-relaxing.

**Comment by Winbagility** [comment]
"If I was a hacker, I would probably try to edit random stuff until it works."
No... this is the behaviour of people that don't know what they are dooing... A script kiddie... This tool is definitlely not for you... Stay at your place, and everything will be cooler :)

"But since I am a software engineer, "
Nice ! I have more lines in my todo list about this project than all the code you commit on github ! C'mon, I'm waiting for your Pull Requests !

" I'd rather rely on the project owner to confirm what is the purpose of that driver"
So next time, don't say something stupid on Twitter BEFORE I respond. 

"I was expecting apologies"
Don't think that people committing their work on github are your b*tch...
This tool is free, open-source, (with bugs), waiting for PR and mostly done on my free time. Give me 10 peoples on this projet, I will do it way better... We are waiting for useful contribution.

"And my terminal does not have a black background, as I don't find it eye-relaxing."
Cool sto' bro ! I'm not here for relaxing, I have work to do with the help of this tool :)

I'm now closing this "Pull Request" !


Just for info, this guy badbuzz and shame with sarcasm just after opening the issue and BEFORE ANY response from me : https://twitter.com/newsoft/status/1130382593470418944
And as you can see, this driver isn't critical at all...

History:
Issue date : 11:12:00 - 19 mai 2019
Tweet date : 11:09:59 - 20 mai 2019
First response : 20:00:00 - 20 mai 2019
